### PR TITLE
Switch to Bot [Version 2]

### LINKED ISSUE #7: Add Eslint
I am a bad dev

### LINKED ISSUE #9: Values fail to get parsed properly in a .NET project.
h30mU3b

### LINKED ISSUE #11: Support for new format of discord webhooks
## Goal

Support all available discord webhook formats

### Context

It seems like your code does not account for webhooks created via the discord app
When I create a webhook, its URL does not match the rules defined in the API:

 https://github.com/IanMitchell/sentrydiscord.dev/blob/471192d217878866b1fcbe358ef994546eac6b20/pages/api/create.js#L9-L12
 
The webhook created via the discordApp:
`https://discordapp.com/api/webhooks/1234/A1B2C3`
I was able to modify the above URL to `https://discord.com/api/webhooks/1234/A1B2C3` which your form has accepted, and I've been able to retrieve events from Sentry

### Extra info
Discord app information: 
  - Release Channel: stable,
  - Build Number: 101451

### LINKED ISSUE #12: Allow Setting Content Field For Webhook
It would be amazing if we could set the content field of a webhook so we could do things such as pinging a certain role that a new issue has been created or something of that sort. I use this integration every single day and I think a feature like this would be really neat.

### LINKED ISSUE #13: Be able to add @mention or @everyone
It would be great if Bot can add @mention or @everyone to make message easier to notices.

### PR DESCRIPTION
**Pull request by IanMitchell**
## Summary

Rewrites this as a Sentry Integration instead of a legacy webhook callback. Utilizes a Discord Bot instead of a Discord Webhook. Will deprecate (but not remove support) for existing webhook functionality. The new version will support resolving, assigning, ignoring, and other actions on posted issues.

## In Depth

I'm rewriting this as a new sentry integration - this gives me access to more modern APIs, and will allow the app to do some cooler things.

1. **Opt-In Event Storage**: Users can opt-in to storing events the service receives. They'll be able to edit sensitive information out of them and submit them to me to use to improve the posted embed (I know different languages have varying quality right now). They can also "retry" posting to the bot if an event fails to post.
2. **Configuring Posts**: Users will be able to select what tags to show and write a message to post when new events are received (useful for pings!)
3. **Preview Sentry Links**: Users can opt-in to a message listener which looks for sentry links, and if found will post a preview embed for the issue. 
4. **Dashboard Configuration**: As a stretch goal, provide a dashboard that admins can use to configure the Discord integration (as an alternative to slash commands)

## Cleanup 

- Fixes #13 
- Fixes #12
- Fixes #11 (no longer uses webhooks)
- Fixes #9 (adds debug mode which will help parser)
- Fixes #7

### CODE REVIEW

**Comment by IanMitchell** [comment]
I'm not sure what the authorization / installation flow for this should be. Gonna jot some scattered thoughts down.

- There are two installation paths, or entry points. The user can either add the integration via Sentry, or they can add the bot via Discord. The bot will have a `/setup` command which, if needed, can redirect the user to Sentry. I'm not sure there is a path to go from Sentry -> Discord bot. Perhaps with the post installation callback?
- How do I connect installation uuids with servers? Would that be part of the callback flow as well?
- What is the uninstallation process like?
- If a bot is removed, can I remove an integration from Sentry?
- If an integration is removed, do I leave a guild?

**Comment by IanMitchell** [comment]
Documenting a flow for future me -

With `/debug` on, events get stored. These should go in a temporary state, viewable on a dashboard per installation. There, users can click into it, edit the JSON to strip sensitive information, and submit it for review in case the parser is bad. They should also be able to click "retry" to try and parse the item again.

**Comment by thewilloftheshadow** [comment]
> * If an integration is removed, do I leave a guild?

Is this bot not going to be able to run multiple integrations in a single server? My current setup with the webhook brings together 3 different projects on Sentry in one category of channels.

**Comment by IanMitchell** [comment]
Posted some high level information in the PR description

**Comment by net-tech** [comment]
Hey @IanMitchell is this still happening?

**Comment by IanMitchell** [comment]
@net-tech I don't think so :( just don't have time to work on it

**Pull request closed without merging**
