### PR TITLE
Add basic support for threads

### PR DESCRIPTION
**Pull request by GeniusTimo**
Hey there 👋

This pull request is quite incomplete, but I wanted to leave this as a suggestion to provide support for sending webhook messages within threads. Perhaps my solution is as simple as suggested but I have not tested this yet - in addition, it lacks any documentation.

Hopefully I'm not the only one looking for a thread-only webhook ✌

### CODE REVIEW

**Comment by IanMitchell** [comment]
Oh interesting. I actually don't know how threads and webhooks work within Discord - is it a webhook on a channel with just the thread_id param passed in?

**Comment by GeniusTimo** [comment]
Yes! https://discord.dev/resources/webhook#execute-webhook

**Comment by IanMitchell** [comment]
Sweet! I will try to take a look at this sometime this week, but I might be a little too busy to get to it - I'm heading out on an international trip for a week, so this might sit until the second week of September, sorry :(

**Comment by GeniusTimo** [comment]
No problem, have a nice vacation ✈

**Comment by IanMitchell** [comment]
Yeah! Lemme do a little bit of testing on it and I will get it in sometime this week. Probably gonna need to get to the other side of July 4th first, but after that I'll try and get it out quickly. Sorry, I guess I lost track of this PR - thank you for the reminder bump

**Comment by IanMitchell** [comment]
Merged into Main, should be deployed soon!

**Comment by GeniusTimo** [comment]
Thank you!

**Pull request closed without merging**
